<a href="https://colab.research.google.com/github/engrdoc/Personal-Projects/blob/main/LottoMax_6Digit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving LOTTOMAX.csv to LOTTOMAX.csv


In [ ]:
#LottoMax Results from 25 Sep 2009 - 8 June 2018
import numpy as np
import pandas as pd
from scipy import stats 
df = pd.read_csv("LOTTOMAX.csv")

In [ ]:
df

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER   DRAW DATE  NUMBER DRAWN 1  \
0     LOTTO MAX            1                0   9/25/2009               5   
1     LOTTO MAX            2                0   10/2/2009               8   
2     LOTTO MAX            3                0   10/9/2009               5   
3     LOTTO MAX            4                0  10/16/2009               4   
4     LOTTO MAX            5                0  10/23/2009               4   
...         ...          ...              ...         ...             ...   
2745  LOTTO MAX          455               48    6/8/2018               1   
2746  LOTTO MAX          455               49    6/8/2018               2   
2747  LOTTO MAX          455               50    6/8/2018               5   
2748  LOTTO MAX          455               51    6/8/2018               5   
2749  LOTTO MAX          455               52    6/8/2018               3   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0                 17              19              25              31   
1                 27              28              29              31   
2                 15              25              38              42   
3                 10              18              20              31   
4                  7              10              12              23   
...              ...             ...             ...             ...   
2745               2               5               8              18   
2746               6               9              11              12   
2747              25              28              34              40   
2748               7              13              16              25   
2749              12              15              17              32   

      NUMBER DRAWN 6  NUMBER DRAWN 7  BONUS NUMBER  
0                 38              46             4  
1                 32              35            11  
2                 46              47            26  
3                 35              44            29  
4                 25              36            18  
...              ...             ...           ...  
2745              23              46             0  
2746              24              40             0  
2747              46              47             0  
2748              26              37             0  
2749              35              43             0  

[2750 rows x 12 columns]

In [ ]:
df.describe()

DRAW NUMBER  SEQUENCE NUMBER  NUMBER DRAWN 1  NUMBER DRAWN 2  \
count  2750.000000      2750.000000     2750.000000     2750.000000   
mean    243.902909        12.569091        6.060364       12.333455   
std     132.933113        12.444045        4.737872        6.498656   
min       1.000000         0.000000        1.000000        2.000000   
25%     139.000000         2.000000        2.000000        7.000000   
50%     251.500000         9.000000        5.000000       11.000000   
75%     352.750000        20.000000        8.000000       16.000000   
max     455.000000        52.000000       33.000000       40.000000   

       NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  NUMBER DRAWN 6  \
count     2750.000000     2750.000000     2750.000000     2750.000000   
mean        18.537455       24.713818       31.070545       37.367273   
std          7.370604        7.649273        7.479676        6.731969   
min          3.000000        5.000000        8.000000       12.000000   
25%         13.000000       19.000000       26.000000       33.000000   
50%         18.000000       25.000000       32.000000       38.000000   
75%         24.000000       30.000000       37.000000       43.000000   
max         42.000000       46.000000       47.000000       48.000000   

       NUMBER DRAWN 7  BONUS NUMBER  
count     2750.000000    2750.00000  
mean        43.695273       4.28400  
std          5.161934      11.28198  
min         15.000000       0.00000  
25%         41.000000       0.00000  
50%         45.000000       0.00000  
75%         48.000000       0.00000  
max         49.000000      49.00000

In [ ]:
#Initially Selecting 1st Number
x1 = df['NUMBER DRAWN 1']
y1 = df['NUMBER DRAWN 2']

In [ ]:
slope, intercept, r, p, std_err = stats.linregress(x1, y1) 

In [ ]:
slope

0.8617628847812366

In [ ]:
intercept

7.1108580953585125

In [ ]:
#Initially Selecting 1 Number only
def predicted_Digit(x1):
  return slope * x1 + intercept 

In [ ]:
mymodel = list(map(predicted_Digit, x1))

In [ ]:
#Now, say choose your first number as: 1
predicted_Digit2 = np.around(predicted_Digit(1))
predicted_Digit2

8.0

In [ ]:
#Initially Selecting 2 Numbers
x2 = df[['NUMBER DRAWN 1','NUMBER DRAWN 2']]
y2 = df['NUMBER DRAWN 3']

In [ ]:
#Using sklearn
from sklearn import linear_model

In [ ]:
regr2 = linear_model.LinearRegression()
regr2.fit(x2,y2)

LinearRegression()

In [ ]:
Intercept = regr2.intercept_
Coefficients = regr2.coef_
print('Intercept :', Intercept)
print('Coefficients: ',Coefficients)

In [ ]:
#Now, say choose your first two numbers as: 1 & 2
predicted_Digit3 = np.around(regr2.predict([[2,17]]))
predicted_Digit3

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([23.])

In [ ]:
#Initially Selecting 3 Numbers
x3 = df[['NUMBER DRAWN 1','NUMBER DRAWN 2', 'NUMBER DRAWN 3']]
y3 = df['NUMBER DRAWN 4']

In [ ]:
regr3 = linear_model.LinearRegression()
regr3.fit(x3,y3)

LinearRegression()

In [ ]:
#Now, say choose your first three numbers as: 1, 2 & 3
predicted_Digit4 = np.around(regr3.predict([[2,17,23]]))
predicted_Digit4

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([28.])

In [ ]:
#Initially Selecting 4 Numbers
x4 = df[['NUMBER DRAWN 1','NUMBER DRAWN 2', 'NUMBER DRAWN 3', 'NUMBER DRAWN 4']]
y4 = df['NUMBER DRAWN 5']

In [ ]:
regr4 = linear_model.LinearRegression()
regr4.fit(x4,y4)

LinearRegression()

In [ ]:
#Now, say choose your first four numbers as: 1, 2, 3 & 4
predicted_Digit5 = np.around(regr4.predict([[2,17,23,28]]))
predicted_Digit5

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([34.])

In [ ]:
#Initially Selecting 5 Numbers
x5 = df[['NUMBER DRAWN 1','NUMBER DRAWN 2', 'NUMBER DRAWN 3', 'NUMBER DRAWN 4','NUMBER DRAWN 5']]
y5 = df['NUMBER DRAWN 6']

In [ ]:
regr5 = linear_model.LinearRegression()
regr5.fit(x5,y5)

LinearRegression()

In [ ]:
#Now, say choose your first five numbers as: 1, 2, 3, 4 & 5
predicted_Digit6 = np.around(regr5.predict([[2,17,23,28,34]]))
predicted_Digit6

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([39.])

In [ ]:
'''
Combining the Regressions above to predict your 6-digit Lotto Combination by selecting only the 1st Number
'''

'\nCombining the Regressions above to predict your 6-digit Lotto Combination by selecting only the 1st Number\n'

In [ ]:
#Now, say choose your first number as:
Digit1 = int(input('Choose you first number (1 - 50):'))
Lotto_Digit2 = np.around(predicted_Digit(Digit1))
Digit2 = Lotto_Digit2.astype(int)
#Digit2
Lotto_Digit3  =np.around(regr2.predict([[Digit1, Digit2]]))
Digit3 = Lotto_Digit3.astype(int)
Digit3 = Digit3[0]
#Digit3
Lotto_Digit4  =np.around(regr3.predict([[Digit1, Digit2, Digit3]]))
Digit4 = Lotto_Digit4.astype(int)
#Digit4[0]
Lotto_Digit5  =np.around(regr4.predict([[Digit1, Digit2, Digit3, Digit4]]))
Digit5 = Lotto_Digit5.astype(int)
#Digit5[0]
Lotto_Digit6  =np.around(regr5.predict([[Digit1, Digit2, Digit3, Digit4, Digit5]]))
Digit6 = Lotto_Digit6.astype(int)
#Digit6[0]

Choose you first number (1 - 50):5


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:746: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.asarray(array, order=order, dty

In [ ]:
LottoMax2 = [Digit1, Digit2]
#LottoMax2
LottoMax3 = np.append(LottoMax2, Digit3)
#LottoMax3
LottoMax4 = np.append(LottoMax3, Digit4)
#LottoMax4
LottoMax5 = np.append(LottoMax4, Digit5)
#LottoMax5
LottoMax_Combo = np.append(LottoMax5, Digit6)
print(f'Your LottoMax Combination is: {LottoMax_Combo}')

Your LottoMax Combination is: [ 5 11 17 23 30 37]
